services:
  simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: simulator
    ports:
      - "8080:8080"

  broker:
    image: apache/activemq-artemis:latest-alpine
    container_name: mars-broker
    ports:
      - "61613:61613"
      - "8161:8161"
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
      - ANONYMOUS_LOGIN=true

  ingestion-service:
    build: ./source/ingestion-service
    container_name: ingestion-service
    ports:
      - "8000:8000"
    depends_on:
      - simulator
      - broker

  rule-engine:
    build: ./source/rule-engine
    container_name: rule-engine
    ports:
      - "8001:8001"
    depends_on:
      - broker
      - simulator
    volumes:
      - ./rules_data:/app/data

  frontend:
    build: ./source/frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - ingestion-service
      - rule-engine